indiefilmrentals/base/urls.py
"""urlconf for the base application"""

from django.conf.urls.defaults import url, patterns, include


urlpatterns = patterns('indiefilmrentals.base.views',
    url(r'^$', 'home', name='home'),
		url(r'^about/', 'about', name='about'),
    url(r'^gear/', 'gear', name='gear'),
    url(r'^services/', 'services', name='services'),
    url(r'^contact/', 'contact', name='contact'),
    url(r'^crews/', 'crews', name='crews'),
    url(r'^crew/terms/', 'crew_terms', name='crew_terms'),
    url(r'^downloads/', 'downloads', name='downloads'),
    url(r'^rental/terms/', 'rental_terms', name='rental_terms'),
		url(r'^faq/', 'faq', name='faq'),
    (r'^accounts/', include('registration.backends.default.urls')),
)

indiefilmrentals/products/urls.py
"""urlconf for the base application"""

from django.conf.urls.defaults import url, patterns, include


urlpatterns = patterns('indiefilmrentals.products.views',
    url(r'^(?P<category>.*?)/(?P<brand>.*?)/(?P<slug>.*?)$', 'product', name='product_view'),
    url(r'^(?P<category>.*?)/(?P<brand>.*?)$', 'brand', name='brand_view'),
    url(r'^(?P<slug>.*?)$', 'category', name='category_detail'),
)

indiefilmrentals/urls.py
""" Default urlconf for indiefilmrentals """

from django.conf import settings
from django.conf.urls.defaults import include, patterns, url
from session_csrf import anonymous_csrf
from django.contrib import admin
from shop import urls as shop_urls # <-- Add this at the top
from haystack.views import SearchView
admin.autodiscover()

# django-session-csrf monkeypatcher
import session_csrf
session_csrf.monkeypatch()


def bad(request):
    """ Simulates a server error """
    1 / 0

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/$', anonymous_csrf(admin.site.admin_view(admin.site.index))),
    (r'^admin/', include(admin.site.urls)),
    #url(r'^', include('debug_toolbar_user_panel.urls')),
    (r'^bad/$', bad),
    (r'^shop/', include(shop_urls)), # <-- That's the important bit
    (r'^rent/', include('indiefilmrentals.products.urls')),
    (r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^search/', SearchView(template='base/search.html'), name='haystack_search'),
    (r'', include('indiefilmrentals.base.urls')),
)

## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

indiefilmrentals/base/models.py
from django.db import models
from shop_simplecategories.models import *

class Link(models.Model):
    anchor = models.CharField(max_length=200)
    url = models.URLField()

    def __unicode__(self):
        return "%s | %s" % (self.anchor, self.url, )

indiefilmrentals/products/models.py
from shop.models import Product
from django.db import models
from indiefilmrentals.base.models import Link

from markdown import markdown
from datetime import datetime
import md5


def my_upload_to(instance, filename):
    prefix = 'products'

    # Get name from FKed model
#    name = instance.product.name

    #filename = md5.new(str(datetime.now())).hexdigest() + '-' + filename
    return "%s/%s" % (prefix, filename)


class Price_Tier(models.Model):
    start_day = models.IntegerField(help_text="Lower limit of price tier's range")
    end_day = models.IntegerField(help_text="Upper limit of price tier's range")
    percent = models.FloatField(help_text="Percentage of product base value to apply for this tier.")

    def __unicode__(self):
        return "Days: %d - %d : %s%%" % (self.start_day, self.end_day, str(self.percent), )

    class Meta:
        verbose_name = "Price Tier"


class Price_Tier_Package(models.Model):
    tier = models.ManyToManyField(Price_Tier)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return "Tier Package: %s" % (self.name,)

    class Meta:
        verbose_name = "Price Tier Package"


class ProductImage(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    image = models.ImageField(upload_to=my_upload_to)

    def __unicode__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name',]

    def __unicode__(self):
        return self.name


class BaseIndieRentalProduct(Product):
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    OHD_ONLY_STATUS = 3
    STATUS_CHOICES = (
                      (LIVE_STATUS, 'Live'),
                      (DRAFT_STATUS, 'Draft'),
                      (OHD_ONLY_STATUS, 'OHD Only'),
                      )

    brand = models.ForeignKey(Brand, null=True, blank=True)

    quantity = models.IntegerField(default=0)

    short_description = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    description_html = models.TextField(null=True, blank=True, editable=False)

    featured_product = models.BooleanField(default=False)

    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT_STATUS, help_text="Only 'Live' status will be publicly displayed.")

    crossSell = models.ManyToManyField('self', null=True, help_text="Products to be cross-sold with this product.", blank=True)

    price_tier = models.ForeignKey(Price_Tier_Package, help_text="The price tier package for this product.", null=True, blank=True)

    links = models.ManyToManyField(Link, help_text="Links to include with this product.", null=True, blank=True)

    ohd_daily = models.CharField(max_length=100,null=True,blank=True)
    ohd_weekly = models.CharField(max_length=100,null=True,blank=True)
    ohd_monthly = models.CharField(max_length=100,null=True,blank=True)

    image = models.ForeignKey(ProductImage, null=True, blank=True)

    ohd_category = models.CharField(max_length=100, null=True, blank=True)
    ohd_subcategory = models.CharField(max_length=100, null=True, blank=True)


    def get_product_image(self):
        try:
            return self.image
        except:
            return None

    class Meta:
        ordering = ['name',]

    @models.permalink
    def get_absolute_url(self):
            return ('indiefilmrentals.products.views.product', (), {
                                        'brand': unicode(self.brand).lower(),
                                        'category': unicode(self.categories.all()[0]).lower() if len(self.categories.all()) else 'none',
                                        'slug': self.slug})

    def save(self, force_insert=False, force_update=False):
        self.description_html = markdown(self.description)
        super(BaseIndieRentalProduct, self).save(force_insert, force_update)


class Lens(BaseIndieRentalProduct):
    class Meta:
        verbose_name_plural = 'Lenses'


class Camera(BaseIndieRentalProduct):
    class Meta:
        pass


class Lighting(BaseIndieRentalProduct):
    class Meta:
        pass

class Audio(BaseIndieRentalProduct):
    class Meta:
        pass


class Monitor(BaseIndieRentalProduct):
    class Meta:
        pass


class Support(BaseIndieRentalProduct):
    class Meta:
        pass


class Accessory(BaseIndieRentalProduct):
    class Meta:
        verbose_name_plural = "Accessories"


class BatteryAndPower(BaseIndieRentalProduct):
    class Meta:
        pass


class DigitalRecorderMediaVTR(BaseIndieRentalProduct):
    class Meta:
        pass


class EditAndTransferSystem(BaseIndieRentalProduct):
    class Meta:
        pass


class Grip(BaseIndieRentalProduct):
    class Meta:
        pass


class MatteBoxFollowFocusFilter(BaseIndieRentalProduct):
    class Meta:
        pass


class MultiCameraSwitcherPackage(BaseIndieRentalProduct):
    class Meta:
        pass


class OtherService(BaseIndieRentalProduct):
    class Meta:
        pass


class TapeStock(BaseIndieRentalProduct):
    class Meta:
        pass


class Teleprompter(BaseIndieRentalProduct):
    class Meta:
        pass


class TimecodeAndSignalConversion(BaseIndieRentalProduct):
    class Meta:
        pass


class TripodDollySupportRig(BaseIndieRentalProduct):
    class Meta:
        pass


class VideoProjection(BaseIndieRentalProduct):
    class Meta:
        pass


class ProductImage(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    image = models.ImageField(upload_to=my_upload_to)

indiefilmrentals/base/views.py
""" Views for the base application """

from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from indiefilmrentals.products.models import *
from shop_simplecategories.models import *
from .utils import send_email_to_ohiohd

def home(request):
    """ Default view for the root """
    return render_to_response('base/home.html',
            {
				'featured': BaseIndieRentalProduct.objects.filter(featured_product=True),
				'homeClass': "current",
            },
        context_instance=RequestContext(request))

def about(request):
    """ Default view for the root """
    return render_to_response('base/about.html',
        {
            'aboutClass': "current",
        },
        context_instance=RequestContext(request))

def gear(request):
    """ Default view for the root """
    return render_to_response('base/gear.html',
            {
                'categories': Category.objects.all().order_by('name').filter(parent_category=None),
				'featured': BaseIndieRentalProduct.objects.filter(featured_product=True),
				'gearClass': "current",
            },
        context_instance=RequestContext(request))

def services(request):
    """ Default view for the root """
    return render_to_response('base/services.html',
        {
            'servicesClass': "current",
        },
        context_instance=RequestContext(request))

def contact(request):
    """ Default view for the root """
    d = {
            'contactClass': "current", 
        }

    if request.method == 'POST':
        kwargs = {
                'name': request.POST.get('name', ''),
                'email': request.POST.get('email',''),
                'phone': request.POST.get('phone',''),
                'message': request.POST.get('message',''),
                'rental': request.POST.get('rental',''),
                'crews': request.POST.get('crews',''),
                'services': request.POST.get('services',''),
                'other': request.POST.get('other',''),
                    }
        send_email_to_ohiohd(**kwargs)
        d['email_sent'] = True

        
    return render_to_response('base/contact.html',
            d,
        context_instance=RequestContext(request))


def crews(request):
    """ Default view for the root """
    return render_to_response('base/crews.html',
        {
            'crewsClass': "current",
        },
        context_instance=RequestContext(request))

def crew_terms(request):
    """ Default view for the root """
    return render_to_response('base/crews.terms.html',
        {
            'crewsClass': "current",
        },
        context_instance=RequestContext(request))

def downloads(request):
    """ Default view for the root """
    return render_to_response('base/downloads.html',
        {},
        context_instance=RequestContext(request))

def rental_terms(request):
    """ Default view for the root """
    return render_to_response('base/rental.terms.html',
        {},
        context_instance=RequestContext(request))

def faq(request):
    """ Default view for the root """
    return render_to_response('base/faq.html',
        {
            'faqClass': "current",
        },
        context_instance=RequestContext(request))

indiefilmrentals/products/views.py
# Create your views here.
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from indiefilmrentals.products.models import *
from shop_simplecategories.models import *
from django.core.context_processors import csrf

def brand(request):
    """ Default view for the root """
    return render_to_response('base/home.html',
        context_instance=RequestContext(request))

def category(request, slug):
    categoryObj = get_object_or_404(Category,slug__iexact=slug)
    products = BaseIndieRentalProduct.objects.filter(categories=categoryObj, status=BaseIndieRentalProduct.LIVE_STATUS)
    subcategories = Category.objects.filter(parent_category=categoryObj)

    return render_to_response('base/category.html',
            {
                'categories': Category.objects.all().order_by('name').filter(parent_category=None),
                'category': categoryObj,
                'products': products,
				'subcategories': subcategories,
				'gearClass': "current",
                'all_subs': Category.objects.all().order_by('parent_category').filter(parent_category__isnull=False),
			},
            context_instance=RequestContext(request))


def product(request, brand, slug, category):
    """ Default view for the nat """
    print 'here'
    productObj = get_object_or_404(BaseIndieRentalProduct,slug=slug, status=BaseIndieRentalProduct.LIVE_STATUS)
    parentCategory = productObj.categories.all()[0]
    if parentCategory.parent_category:
        parentCategory = parentCategory.parent_category

    c = RequestContext(request)
    #c.update(csrf(c))
    return render_to_response('base/product.html',
        {
            'product':productObj,
            'categories': Category.objects.all(),
			'category_link': parentCategory.get_absolute_url(),
			'gearClass': "current",
        },
        context_instance=c)

indiefilmrentals/base/templates/base/_template.html
{% extends "base.html" %}

{% block page_title %}Good Times{% endblock %}
{% block class %}services{% endblock %}

{% block content %}

<!-- markup -->

{% endblock %}

indiefilmrentals/base/templates/base/category.html
{% extends "base.html" %}

{% block page_title %}{{ category.name }}{% endblock %}
{% block class %}gear{% endblock %}

{% block content %}
<!-- Start category -->
<div id="hero">
	<div class="container clearfix">
		<h2>We have Ohio's <span class="ltblue">largest selection</span> of film, HD &amp; cine <span class="yellow">cameras and lenses.</span></h2>
	</div>	
</div>

<!-- sixteen column block for 5 column of product -->
<div id="main-content">
	<div class="container clearfix">
		<div class="products twelve columns alpha">
			
			<h1>{{ category.name }}</h1>
			{% with products=category.get_products %}					
				{% for product in products %}
					<!-- print out category products -->
					<div class="three columns product">
						<a href="{{product.get_absolute_url}}" class="img-block">
							<img src="{{ product.get_product_image.image.url }}" alt="{{ product.get_product_image.description }}">
						</a>
						<a href="{{product.get_absolute_url}}">{{product.name}}</a>
					</div>							
					{% if forloop.counter|divisibleby:"4" and not forloop.last %}
						<hr>
					{% endif %}
				{% endfor %}
			{% endwith %}
			<div class="sub-category clearfix">				
				{% for subcategory in subcategories %}
					{% if not forloop.first %}
						<hr>
					{% endif %}
					<a href="{{subcategory.get_absolute_url}}"><h3>{{subcategory.name}}</h3></a>
					
					{% if subcategory.get_products %}
						{% with products=subcategory.get_products %}					
							{% for product in products %}
								<!-- print out subcategory products -->
								<div class="three columns product">
									<a href="{{product.get_absolute_url}}" class="img-block">
										<img src="{{ product.get_product_image.image.url }}" alt="{{ product.get_product_image.description }}">
									</a>
									<a href="{{product.get_absolute_url}}">{{product.name}}</a>
								</div>							
								{% if forloop.counter|divisibleby:"4" and not forloop.last %}
									<hr>
								{% endif %}
							{% endfor %}
						{% endwith %}
					{% endif %}
                {% endfor %}
			</div><!-- End Sub Category -->
			
		</div><!-- products -->
		<div class="four columns omega sidebar">
			<h3>Product Categories</h3>
			<ul id="gear-nav">
				{% for category in categories %}
					<li class="category-parent">
						<a href="{{ category.get_absolute_url }}"><i></i>{{ category.name }}</a>
						<ul class="sub-nav" style="display: none">
							{% for sub in all_subs %}
								{% ifequal sub.parent_category.name category.name %}
									<li><a href="{{ sub.get_absolute_url }}"><i></i>{{ sub.name }}</a></li>
								{% endifequal %}
							{% endfor %}
						</ul>
					</li>
                {% endfor %}
			</ul>
			
		</div><!-- End Product Sidebar -->

	</div><!-- End Container -->
</div><!-- End main content -->
<!-- End category -->
{% endblock %}

indiefilmrentals/base/templates/base/contact.html
{% extends "base.html" %}

{% block page_title %}Contact Us{% endblock %}
{% block class %}contact{% endblock %}

{% block content %}

<div id="main-content">
	<div class="container clearfix">
		<div class="twelve columns alpha equal">
			<h1>Contact <span class="yellow">Us</span></h1>
						
<h2>{% if email_sent %}
Your Email has been sent.
{% endif %}</h2>

			<p>Whether you are interested in equipment rental, hiring a crew or producing a video, there are many ways to reach us. Use the form below to send us a message, or call us at one of the numbers on the right.  We look forward to working with you.</p>
			
			<div class="row well">
				<form id="contact" method="post"  class="clearfix" action="/contact/">
                    {% csrf_token %}
					<div class="form-col1">
						<label for="name">Name: *</label>
						<input name="name" type="text" id="name" required />
						<label for="email">Email: *</label>
						<input name="email" type="email" id="email" required  />
						<label for="email">Phone:</label>
						<input name="phone" type="text" id="phone" />
				
						<fieldset>
					    	<label>Interested in: *</label>

						    <label for="equipment">
						      <input name="rental" type="checkbox" id="equipment" value="Equipment Rental" />
						      <span>Equipment Rental</span>
						    </label>

						    <label for="crews">
						      <input name="crews" type="checkbox" id="crews" value="Production Crews" />
						      <span>Production Crews</span>
						    </label>
			
							<label for="services">
						      <input name="services" type="checkbox" id="services" value="Production Services" />
						      <span>Production Services</span>
						    </label>
			
							<label for="other">
						      <input name="other" type="checkbox" id="services" value="Other" />
						      <span>Other</span>
						    </label>
						</fieldset>
					</div>
					
					<div class="form-col2">
						<label for="message">Message:</label>
						<textarea name="message" id="message"></textarea>
						<small>(*) denotes required field</small>
						<button type="submit" id="contact-submit">Send Message</button>
					</div>
				</form>
			</div><!-- End Form Row -->
						
		</div><!-- End Container -->
				
		<div class="four columns omega sidebar equal">
			<h3>Location</h3>
			
			<p><strong>Ohio HD Video @The Backlot</strong><br />
				3465 Noe Bixby Rd<br />
				Columbus, Ohio 43232
			</p>
				
			<p>Pickup / Drop-off Gear<br />
				Open Weekdays 9am - 5pm</p>
				
			<p>
				<span class="label"><strong>Phone:</strong></span> 614-656-1162<br />
				<span class="label"><strong>Fax:</strong></span> 614-656-4343<br />
				<span class="label"><strong>Email:</strong></span> info@ohiohdvideo.com	
			</p>
			
			<p>Located 15 minutes South East of Downtown Columbus. <a href="downloads/OhioHD-directions.pdf">Download directions if you need help finding us.</a></p>
			
			<small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Ohio+Hd+Video,+Noe+Bixby+Road,+Columbus,+OH&amp;aq=0&amp;oq=Ohio+HD&amp;sll=39.907498,-82.870903&amp;sspn=0.143661,0.28307&amp;gl=us&amp;ie=UTF8&amp;hq=Ohio+Hd+Video,&amp;hnear=Noe+Bixby+Rd,+Columbus,+Ohio&amp;t=m&amp;cid=14368856923638474090&amp;ll=39.916583,-82.871075&amp;spn=0.059247,0.119991&amp;z=11&amp;iwloc=A">View Larger Map</a></small>
			<iframe width="200" height="150" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="border: 1px solid #ccc;" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Ohio+Hd+Video,+Noe+Bixby+Road,+Columbus,+OH&amp;aq=0&amp;oq=Ohio+HD&amp;sll=39.907498,-82.870903&amp;sspn=0.143661,0.28307&amp;gl=us&amp;ie=UTF8&amp;hq=Ohio+Hd+Video,&amp;hnear=Noe+Bixby+Rd,+Columbus,+Ohio&amp;t=m&amp;cid=14368856923638474090&amp;ll=39.916583,-82.871075&amp;spn=0.059247,0.119991&amp;z=11&amp;iwloc=A&amp;output=embed"></iframe>
			
		</div><!-- End Product Sidebar -->
	</div><!-- End Container -->
</div><!-- End Main-Content -->

{% endblock %}

indiefilmrentals/base/templates/base/nat.html
{% extends "base.html" %}

{% block page_class %}home-page{% endblock %}
{% block content %}
<!-- sixteen column block for 5 column of product -->
<div class="sixteen columns">
	<div class="mod-horiz"></div>
	<div class="box">
		<div class="box-heading">{{ name }}</div>
		<div class="box-content">
		{% for product in cameras %}
			<div class="box-product">
				<div>
					<div class="image clear-both"><a href="#{{product_link}}"><img src="{{product_image}}" alt="iMac" />{{product.name}}</a></div>
					<div class="name clear-both"><a href="#{{product_link}}">{{product_name}}</a></div>
					<div class="price">{{product_price}}</div>
				<div class="cart"><a onclick="addToCart({{product_id}});" class="button"><span>Add to Cart</span></a></div>
			</div>
		{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

indiefilmrentals/base/templates/base/product.html
{% extends "base.html" %}

{% load mathtags %}

{% block page_title %}{{ product.name }}{% endblock %}
{% block class %}product-item{% endblock %}

{% block content %}
<div id="main-content">
    <div class="container clearfix">
	
        <div class="twelve columns products alpha">
            <div id="breadcrumbs" class="row">
                <a href="#">Gear Rental</a><span class="seperator">/</span><a href="{{ category_link }}">{{ product.ohd_category }}</a><span class="seperator">/</span>{{ product.name }}
            </div>
            <h1>{{ product.name }}</h1>
            <div class="row">
                <div id="imgs-wrap" class="seven columns clearfix alpha">
                    {% if product.get_product_image %}
                        <img src="{{ product.get_product_image.image.url }}" alt="{{ product.get_product_image.description|striptags }}" />
                    {% else %}
                        <img src="/static/img/fpo-80x80.jpg" width="400" height="286" />
                    {% endif  %}
                </div>
                <div class="pricing">
                    <h5>Prices</h5>
                    <ul>
                        <li><span class="duration">Day:</span> ${{product.ohd_daily}}</li>
                        <li><span class="duration">Week:</span> ${{product.ohd_weekly}}</li>
                        <li><span class="duration">Month:</span> ${{product.ohd_monthly}}</li>
                    </ul>
                    <a href="/contact/" class="button">Inquire about this gear</a>
                </div>
            </div>
    
            <div class="row description">
                {% if product.description %}
                    <h3>Description</h3>
                    {% autoescape off %}
                        {{product.description}}
                    {% endautoescape %}
                {% endif %}
            </div>
        </div><!-- End products -->
    
        <div class="four columns omega sidebar">
            <h3>Product Categories</h3>
            <ul id="gear-nav">
                {% for category in categories %}
                    {% if not category.parent_category %}
                        <li class="category-parent">
                            <a href="{{ category.get_absolute_url }}"><i></i>{{ category.name }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div><!-- End Product Sidebar -->
        
    </div><!-- End Container -->
</div><!-- End Main-Content -->






<!--div class="sixteen columns category-head row">
    <h1>{{ product.name }}</h1>
    <div class="breadcrumb">
        <a href="http://wedevu.com/products/responsive/index.php?route=common/home">Home</a>
        » <a href="http://wedevu.com/products/responsive/index.php?route=product/product&amp;product_id=40">Lenses</a>
    </div>
</div>
<div class="sixteen columns clearfix">

   <div class="twelve columns alpha omega product-info">
      <div class="mod-horiz">
      </div>

      <div class="eight columns alpha">
         <div class="image">
            {% if product.get_product_image %}
                <img src="{{ product.get_product_image.image.url }}" title="{{ product.get_product_image.description|striptags }}" />
            {% else %}
                <img src="/static/img/fpo-80x80.jpg" />
            {% endif  %}
         </div>
         {% if product.productimage_set.all|length > 1 %}
         <div class="image-additional no-mobile">
            {% for subimage in product.productimage_set.all %}
            <a href="#" title="" class="fancybox">
                <img src="{{ subimage.image.url }}" title="{{ subimage.description|striptags }}" />
            </a>
            {% endfor  %}
         </div>
         {% endif %}
      </div>

      <div class="four columns omega">
          <form action="{% url cart_item_add %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="add_item_id" value="{{ product.id }}" />
              <a id="button-cart" class="button" onclick="$(this).parent().submit();return false;"><span>Rent Now</span></a>
        </form>
         <p>
            <span>${{product.get_price|mult:"4"}} for 4 days</span>
            <br /><span>4-29 day rental</span>
            <br /><span>+$29 shipping</span>
         </p>
      </div>

      <div class="ten columns clearfix alpha omega description">
    
        {% if product.description %}
            <h2>Description</h2>
            {% autoescape off %}
                {{product.description}}
            {% endautoescape %}
        {% endif %}
        
        {% if product.links.all.count > 0 %}
            <h3>Links</h3>
            <ul>
                {% for link in product.links.all %}
                <li><a href="{{ link.url }}">{{link.anchor}}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
         
        <div class="x6 l rr pricing vp">
            <div class="x">
                <h2>Pricing</h2>
                <table class="pricing data">
                    <tbody>
                        <tr>
                            <th width="50%">Rental Period</th>
                            <th width="25%" class="r">Price</th>
                            <th width="25%" class="r">Day Rate</th>
                        </tr>
                    </tbody>
                </table>
                {{ product.price_tier }}
                <table class="pricing data">
                    <tbody>
                        <tr>
                            <th width="25%">Rental Period</th>
                            <th width="25%" class="r">Waiver Price</th>
                            <th width="25%" class="r">Total Price</th>
                            <th width="25%" class="r">Day Rate</th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="x6 l rl shipping vp">
           <div class="x">
              <h2>Shipping</h2>
           </div>
        </div>
        
      </div>
      <div class="mod-horiz">
      </div>
   </div>

   <div class="four columns omega no-mobile">
    {% if product.crossSell.all %}
        <div style="padding-left: 10px;">
            <div class="box">
                <div class="box-heading">Related</div>
                <div class="box-content">
                    <div class="box-product">
                        <div>
                            <div class="image clear-both"><a href="#"><img src="/static/img/fpo-80x80.jpg" alt="alt" /></a></div>
                            <div class="name clear-both"><a href="#">{{product.name}}</a></div>
                            <div class="price">${{product.get_price}}</div>
                            <div class="cart"><a onclick="alert('atb')" class="button"><span>Add to Cart</span></a></div>
                        </div>
                        <ul>
                            {% for xsell in product.crossSell.all %}
                                <li><a href="{{ xsell.get_absolute_url}}">{{ xsell }}</a></li>
                            {% endfor %}
                        </ul> 
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
   </div>
</div-->
{% endblock %}